# Project: Projeto5
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/Users/Admin/AppData/Local/Temp/RarSFX0/lib" -mwindows -lalleg_s -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lole32 -ldinput -lddraw -ldxguid -lwinmm -ldsound 
INCS =  -I"C:/Users/Admin/AppData/Local/Temp/RarSFX0/include" 
CXXINCS =  -I"C:/Users/Admin/AppData/Local/Temp/RarSFX0/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/Admin/AppData/Local/Temp/RarSFX0/include/c++/3.4.2/backward"  -I"C:/Users/Admin/AppData/Local/Temp/RarSFX0/include/c++/3.4.2/mingw32"  -I"C:/Users/Admin/AppData/Local/Temp/RarSFX0/include/c++/3.4.2"  -I"C:/Users/Admin/AppData/Local/Temp/RarSFX0/include" 
BIN  = jogo.exe
CXXFLAGS = $(CXXINCS) -DALLEGRO_STATICLINK 
CFLAGS = $(INCS) -DALLEGRO_STATICLINK 
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before jogo.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "jogo.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
